### ISSUE TITLE
Schreibfehler im Dialog "Gleich gehts los"

### ISSUE THREAD

**Issue by breitema** [grapedevelopment/grape_module_canvassing#3]
Bei der Auswahlliste "Bist Du alleine unterwegs oder mit Begleitung"
ist ein Datensatz
"Mit eine**m** Frau..." drin. muss "Mit einer Frau.." heißen

Außerdem ist da ein Datensat "mit Vorname Nachname" drin. Vermutlich ein Testdatensatz. Sollte dann für den Produktivbetrieb entfernt werden. 
![tzt_mit_einem_frau](https://user-images.githubusercontent.com/43267242/53283102-837e3880-3741-11e9-9cf3-f348326721ed.png)

**Comment by mielert** [comment]
Erledigt
